require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'POPPINS' do
  
  rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
    
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :subspecs => [
    'DevSupport',
    'Core',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTText'
  ])

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-mapbox-navigation', :path => '../node_modules/@homee/react-native-mapbox-navigation'

  target 'POPPINSTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    $RNMBNAV.pre_install(installer)
    # any other pre install hooks here
  end

  post_install do |installer|
    $RNMBNAV.post_install(installer)
    # any other post install hooks here
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.74.0' })
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'POPPINS-tvOS' do
  # Pods for POPPINS-tvOS

  target 'POPPINS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
