require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'POPPINS' do
  
  rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
    
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'RNOpenEspecificsSettings', :path => '../node_modules/react-native-open-especifics-settings'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  target 'POPPINSTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.74.0' })
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'POPPINS-tvOS' do
  # Pods for POPPINS-tvOS

  target 'POPPINS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
