// MERCHANT CONSTANTS
export const GET_ALL_MERCHANT_PROCESSING = "GET_ALL_MERCHANT_PROCESSING" 
export const GET_ALL_MERCHANT_PROCESSED = "GET_ALL_MERCHANT_PROCESSED" 





// DEFAULT ERROR
export const ERROR = "ERROR"